apiVersion: v2
name: kube-green
description: kube-green helm chart
icon: https://raw.githubusercontent.com/kube-green/kube-green/main/logo/logo.svg

type: application

# Aligned to what's deployed in keos-kubegreen (helm.sh/chart: kube-green-0.7.19)
version: 0.7.19
appVersion: "0.7.19"
