version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - errname
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - maintidx
    - misspell
    - mnd
    - noctx
    - nolintlint
    - nosprintfhostport
    - revive
    - tagliatelle
    - unconvert
    - unparam
    - whitespace
  settings:
    mnd:
      checks:
        - case
        - condition
        - return
    revive:
      rules:
        - name: var-declaration
          disabled: true
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: comment-spacings
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - maintidx
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - zz.deepcopy
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz.deepcopy
      - third_party$
      - builtin$
      - examples$
