apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kube-green
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kube-green
  name: kube-green-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: kube-green
    control-plane: controller-manager
status:
  loadBalancer: {}
