{{- if and (not .Values.certManager.enabled) .Values.jobsCert.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include  "kube-green.webhook.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: {{ include  "kube-green.webhook.name" . }}
    {{- include "kube-green.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
    resourceNames:
      - {{ include "kube-green.webhook.secret.name" . }}
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
{{ end -}}
