# permissions for end users to view sleepinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sleepinfo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-green
    app.kubernetes.io/part-of: kube-green
    app.kubernetes.io/managed-by: kustomize
  name: sleepinfo-viewer-role
rules:
- apiGroups:
  - kube-green.com
  resources:
  - sleepinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-green.com
  resources:
  - sleepinfos/status
  verbs:
  - get
