{{- if and (not .Values.certManager.enabled) .Values.jobsCert.enabled .Values.manager.metrics.enabled .Values.manager.metrics.secure }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-green.metrics.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    kubernetes.io/enforce-mountable-secrets: "true"
  labels:
    app: {{ include "kube-green.metrics.serviceAccount.name" . }}
    {{- include "kube-green.labels" . | nindent 4 }}
automountServiceAccountToken: false
secrets:
- name: {{ include "kube-green.metrics.secret.name" . }}
  kind: Secret
{{- end }}
