{{- if .Values.manager.auth.enabled }}
{{- $jwtName := .Values.manager.auth.jwtSecretName -}}
{{- $usersName := .Values.manager.auth.usersSecretName -}}
{{- $existingJwt := (lookup "v1" "Secret" .Release.Namespace $jwtName) -}}
{{- $existingUsers := (lookup "v1" "Secret" .Release.Namespace $usersName) -}}
---
# JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jwtName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-green.labels" . | nindent 4 }}
    component: auth
type: Opaque
stringData:
  secret: {{- if .Values.manager.auth.jwtSecret }} {{ .Values.manager.auth.jwtSecret | quote }}
          {{- else if $existingJwt }} {{ (index $existingJwt.data "secret") | b64dec | quote }}
          {{- else }} {{ randAlphaNum 32 | quote }}
          {{- end }}
---
# Users Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $usersName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-green.labels" . | nindent 4 }}
    component: auth
type: Opaque
stringData:
  users: |
    {{- if .Values.manager.auth.defaultUsers }}
{{ .Values.manager.auth.defaultUsers | nindent 4 }}
    {{- else if $existingUsers }}
{{ (index $existingUsers.data "users") | b64dec | nindent 4 }}
    {{- else }}
    admin:$2b$12$Nh3tDgFg2A23gQMYJK7g6O/hHbRUqoNWEdtsyom0iUDjawpMPaHFm:admin
    {{- end }}
{{- end }}
