{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-green-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ printf "kube-green-webhook-service.%s.svc" .Release.Namespace }}
  - {{ printf "kube-green-webhook-service.%s.svc.cluster.local" .Release.Namespace }}
  issuerRef:
    kind: Issuer
    name: kube-green-selfsigned-issuer
  secretName: {{ include "kube-green.webhook.secret.name" . }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kube-green-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{ end -}}
