{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-green.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-green.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "kube-green.selectorLabels" . | nindent 4 }}
    component: frontend
{{- end }}
