on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
name: Security
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
